services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mariadb-data:/var/lib/mysql
    ports:
      - "3306:3306"

  flask_api:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: flask_api
    restart: always
    ports:
      - "5001:5001"
    depends_on:
      - mariadb
    environment:
      - FLASK_APP=app.py
      # uncomment for production
     #  - FLASK_ENV=production

volumes:
  mariadb-data:
    driver: local
